env:
  node: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
parserOptions:
  ecmaVersion: latest
  sourceType: module
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
settings:
  import/core-modules: ["aws-sdk", "aws-lambda"]
