service: binance-assets-buyer
frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-bundle
  - serverless-offline

package:
  individually: true

custom:
  bundle:
    sourcemaps: false
    caching: true

provider: ${file(provider.yml)}

functions:
  manager:
    handler: functions/manager.handler
    events:
      - schedule:
          rate: cron(0 0 * * ? *)
          input:
            symbol: ETHUSDT
            quoteOrderQty: 10 # // 10 USDT
      - schedule:
          rate: cron(0 0 * * ? *)
          input:
            symbol: MATICUSDT
            quoteOrderQty: 10 # // 10 USDT
      - schedule:
          rate: cron(0 0 * * ? *)
          input:
            symbol: DOGEUSDT
            quoteOrderQty: 10 # // 10 USDT
      - schedule:
          rate: cron(0 0 * * ? *)
          input:
            symbol: SHIBUSDT
            quoteOrderQty: 10 # // 10 USDT
  walletPerformance:
    handler: functions/income-sender.handler
    events:
      - schedule:
          rate: cron(0 18 * * ? *)
          input:
            symbols: BTCUSDT,ETHUSDT,MATICUSDT,DOGEUSDT,SHIBUSDT
